### ISSUE TITLE
Missing fonts during build flatsphere.

### ISSUE THREAD

**Issue by spairo1741** [d4rkmen/flatsphere#1]
- Working with IDF v5.5.5 and Eclipse.
- Errors regarding missing fonts of various sizes occur during the compilation of flatsphere v1.1.
- I select these fonts in the LVGL section of sdkconfig, but they are missing again after the build 
		(checked sdkconfig.json in the /build directory).
Example error:
D:/esp32/workspace/flatsphere/main/ui/screens/ui_SetTime.c:63:49: error: 'lv_font_montserrat_30' undeclared (first use in this
 function); did you mean 'lv_font_montserrat_14'?
   63 |     lv_obj_set_style_text_font(ui_RollerHours, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
- Font sizes: 20, 30, 38, 40.

**Comment by spairo1741** [comment]
- I downloaded files from the internet, but I didn't realize that my Windows 10 Pro computer wasn't locked and was displaying 
"This file is from another computer and may be locked" in Windows 10. Before using it, you need to unlock it.
- After blocking it in the registry, compilation goes smoothly...
- But after flashing and running the program, the clock on the monitor shows "5 minutes past ten" but I can't hear any sound.
- Is this how it should be, or is it a demo version?
